import { VariantConfig } from "../types";

export const newYorkVariant: VariantConfig = {
  name: "New York",
  slug: "new-york",
  locations: [
    { id: "lincoln-center", name: "Lincoln Center", x: 180, y: 75 },
    { id: "central-park", name: "Central Park", x: 440, y: 55 },
    { id: "times-square", name: "Times Square", x: 230, y: 185 },
    { id: "united-nations", name: "United Nations", x: 600, y: 145 },
    { id: "chelsea", name: "Chelsea", x: 140, y: 290 },
    { id: "empire-state", name: "Empire State", x: 370, y: 260 },
    { id: "gramercy-park", name: "Gramercy Park", x: 540, y: 310 },
    { id: "greenwich-village", name: "Greenwich Village", x: 190, y: 410 },
    { id: "east-village", name: "East Village", x: 430, y: 405 },
    { id: "soho", name: "Soho", x: 240, y: 510 },
    { id: "lower-east-side", name: "Lower East Side", x: 510, y: 480 },
    { id: "chinatown", name: "Chinatown", x: 360, y: 575 },
    { id: "wall-street", name: "Wall Street", x: 260, y: 650 },
    { id: "brooklyn", name: "Brooklyn", x: 640, y: 610 },
  ],
  routes: [
    { id: 0, from: "lincoln-center", to: "central-park", length: 2, color: "red", claimedBy: null },
    { id: 1, from: "lincoln-center", to: "times-square", length: 2, color: "orange", claimedBy: null },
    { id: 2, from: "central-park", to: "times-square", length: 2, color: "black", claimedBy: null },
    { id: 3, from: "central-park", to: "united-nations", length: 2, color: "pink", claimedBy: null },
    { id: 4, from: "times-square", to: "empire-state", length: 1, color: "blue", claimedBy: null },
    { id: 5, from: "times-square", to: "chelsea", length: 2, color: "wild", claimedBy: null },
    { id: 6, from: "united-nations", to: "empire-state", length: 2, color: "green", claimedBy: null },
    { id: 7, from: "united-nations", to: "gramercy-park", length: 2, color: "yellow", claimedBy: null },
    { id: 8, from: "chelsea", to: "empire-state", length: 2, color: "red", claimedBy: null },
    { id: 9, from: "chelsea", to: "greenwich-village", length: 2, color: "blue", claimedBy: null },
    { id: 10, from: "empire-state", to: "gramercy-park", length: 1, color: "orange", claimedBy: null },
    { id: 11, from: "greenwich-village", to: "east-village", length: 2, color: "black", claimedBy: null },
    { id: 12, from: "greenwich-village", to: "soho", length: 2, color: "green", claimedBy: null },
    { id: 13, from: "gramercy-park", to: "east-village", length: 2, color: "white", claimedBy: null },
    { id: 14, from: "east-village", to: "lower-east-side", length: 1, color: "black", claimedBy: null },
    { id: 15, from: "soho", to: "chinatown", length: 2, color: "pink", claimedBy: null },
    { id: 16, from: "soho", to: "wall-street", length: 2, color: "yellow", claimedBy: null },
    { id: 17, from: "lower-east-side", to: "brooklyn", length: 3, color: "wild", claimedBy: null },
    { id: 18, from: "lower-east-side", to: "chinatown", length: 1, color: "blue", claimedBy: null },
    { id: 19, from: "chinatown", to: "wall-street", length: 1, color: "green", claimedBy: null },
    { id: 20, from: "chinatown", to: "brooklyn", length: 3, color: "orange", claimedBy: null },
    { id: 21, from: "wall-street", to: "brooklyn", length: 3, color: "red", claimedBy: null },
    { id: 22, from: "empire-state", to: "east-village", length: 2, color: "yellow", claimedBy: null },
  ],
  destinationTickets: [
    { id: 0, from: "lincoln-center", to: "brooklyn", points: 8 },
    { id: 1, from: "central-park", to: "brooklyn", points: 7 },
    { id: 2, from: "lincoln-center", to: "wall-street", points: 6 },
    { id: 3, from: "times-square", to: "brooklyn", points: 5 },
    { id: 4, from: "central-park", to: "chinatown", points: 5 },
    { id: 5, from: "chelsea", to: "brooklyn", points: 5 },
    { id: 6, from: "united-nations", to: "wall-street", points: 5 },
    { id: 7, from: "times-square", to: "soho", points: 3 },
    { id: 8, from: "central-park", to: "gramercy-park", points: 3 },
    { id: 9, from: "lincoln-center", to: "greenwich-village", points: 3 },
    { id: 10, from: "empire-state", to: "chinatown", points: 3 },
    { id: 11, from: "chelsea", to: "lower-east-side", points: 4 },
    { id: 12, from: "greenwich-village", to: "brooklyn", points: 4 },
    { id: 13, from: "united-nations", to: "east-village", points: 3 },
    { id: 14, from: "gramercy-park", to: "chinatown", points: 3 },
    { id: 15, from: "times-square", to: "east-village", points: 2 },
    { id: 16, from: "empire-state", to: "soho", points: 2 },
    { id: 17, from: "chelsea", to: "east-village", points: 3 },
  ],
  maxPlayers: 4,
  minPlayers: 2,
  startingTaxiCabs: 15,
  startingHandSize: 2,
  initialDestinationCount: 2,
  minInitialDestinationsToKeep: 1,
  drawDestinationCount: 2,
  minDestinationsToKeep: 1,
  endGameTaxiThreshold: 2,
  cardsPerColor: 5,
  wildCards: 4,
  routePointValues: {
    1: 1,
    2: 2,
    3: 4,
    4: 7,
  },
};
